// Generated by CoffeeScript 1.4.0

$(function() {
  var getURL, sendRequest, validateURL;
  getURL = function(s) {
    if (s.substr(0, 7) !== "http://" && s.substr(0, 8) !== "https://") {
      s = "http://" + s;
    }
    return s;
  };
  validateURL = function(s) {
    var urlregex;
    urlregex = new RegExp("^(http|https|ftp)://([a-zA-Z0-9.-]+(:[a-zA-Z0-9.&amp;%$-]+)*@)*((25[0-5]|2[0-4][0-9]|[0-1]{1}[0-9]{2}|[1-9]{1}[0-9]{1}|[1-9]).(25[0-5]|2[0-4][0-9]|[0-1]{1}[0-9]{2}|[1-9]{1}[0-9]{1}|[1-9]|0).(25[0-5]|2[0-4][0-9]|[0-1]{1}[0-9]{2}|[1-9]{1}[0-9]{1}|[1-9]|0).(25[0-5]|2[0-4][0-9]|[0-1]{1}[0-9]{2}|[1-9]{1}[0-9]{1}|[0-9])|([a-zA-Z0-9-]+.)*[a-zA-Z0-9-]+.(com|edu|gov|int|mil|net|org|biz|arpa|info|name|pro|aero|coop|museum|[a-zA-Z]{2}))(:[0-9]+)*(/($|[a-zA-Z0-9.,?'\\+&amp;%$#=~_-]+))*$");
    return urlregex.test(s);
  };
  sendRequest = function(url) {
    console.log('sending request');
    return $.ajax({
      data: {
        longurl: url
      },
      url: "lengthen.php",
      complete: function(XMLHttpRequest, textStatus) {
        console.log(XMLHttpRequest.responseText);
        return $(".result").html(XMLHttpRequest.responseText);
      }
    });
  };
  return $('form').submit(function(e) {
    var url;
    e.preventDefault();
    url = getURL($("#longurl").val());
    if (validateURL(url)) {
      return sendRequest(url);
    } else {
      return alert('Error: Invalid URL');
    }
  });
});
